language: node_js
node_js:
  - 6

before_install:
  # Only run build in 2 cases:
  # - Build initiated by PR
  # - Build not initiated by PR but for a merge to the master branch
  - if ["$TRAVIS_BRANCH" != "master"] && ["$TRAVIS_PULL_REQUEST" != "true"]; then echo "Only PR's or the master branch will be built." && exit 2; fi

script:
  - yarn test -- --coverage

after_success:
  # Deploy to GitHub Pages on a successful build for the master branch
  - git config --global user.email "sampi+travisci@thelaundromatcafe.com"
  - git config --global user.name "Travis CI"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "Deploying master branch to gh-pages" && yarn deploy; fi

cache:
  yarn: true
  directories:
    - node_modules
