language: node_js
node_js:
  - 6

before_install:
  # Only run build in 2 cases:
  # - Build initiated by PR
  # - Build not initiated by PR but for a merge to the master branch
  - if ["$TRAVIS_BRANCH" != "master"] && ["$TRAVIS_PULL_REQUEST" != "true"]; then echo "Only PR's or the master branch will be built." && exit 2; fi

script:
  - yarn test -- --coverage

cache:
  yarn: true
  directories:
    - node_modules
